version: '3'

services:

  php-fpm:
    image: php:fpm-alpine
    volumes:
      - ${PWD}:/var/www

  nginx:
    image: nginx
    volumes:
      - ${PWD}:/var/www
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/sites/:/etc/nginx/sites-available
      - ${PWD}/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
